name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the these branches.
on:
  push:
    branches:
      - master
      - 'epic/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'epic/**'
      - 'release/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          # Check-out the submodules as well
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Clean compile
        run: mvn -f pom.xml clean compile

      # Ignore test failures so that all tests are run
      # The publish report step will take care of failing the build if needed
      # Use jacoco to prepare test coverage report for sonar
      - name: Execute tests
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true

      - name: Publish test report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true
          fail_if_no_tests: false

      - name: Generate test coverage report
        run: mvn org.jacoco:jacoco-maven-plugin:report
